### ISSUE TITLE
Text to Speech请求支持自选文件格式

### ISSUE THREAD

**Issue by Leegenux** [jaywcjlove/DevHub#8]
如题，caf文件格式不是一个通用的文件格式，可否提供其他文件格式的选项

**Comment by jaywcjlove** [comment]
@Leegenux 后面应该会弄到独立应用中 https://apps.apple.com/cn/app/textsound-saver/id6478511402

**Comment by jaywcjlove** [comment]
毕竟我的收费项目不多 https://wangchujiang.com/TextSoundSaver/

**Comment by Leegenux** [comment]
明白了，谢谢
