### ISSUE TITLE
超赞的开发工具，在苹果 AppStore 发布需要 app 备案吗？

### ISSUE THREAD

**Issue by PublicWorld** [jaywcjlove/DevHub#9]
楚江王你好，我看好像四月起需要备案并显示备案号在app里，似乎咱这APP还没备案，审核是咋通过的呀？ 
我也想尝试写个工具又嫌备案忒麻烦

**Comment by jaywcjlove** [comment]
@PublicWorld 如果你不添加 手机应用，是不用备案的

**Comment by PublicWorld** [comment]
感谢~ 我试试
